# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:14

pipelines:
  branches:
    master:
      - step:
          name: 'Deployment to Production'
          deployment: production
          script:
            - echo 'main'
            - export DIPLOY_COMMAND="cd app&&rm -rf "$BITBUCKET_REPO_SLUG"&&git clone -b "$BITBUCKET_BRANCH" --single-branch "$BITBUCKET_GIT_SSH_ORIGIN"&&cd "$BITBUCKET_REPO_SLUG"&&source deploy-prod.sh;"
            - ssh -i ~/.ssh/config $USER_NAME@$PROD_ADDRESS -p $PORT $DIPLOY_COMMAND
    development:
      - step:
          name: 'Test Deployment'
          deployment: staging
          script:
            - echo 'dev'
            - export DIPLOY_COMMAND="cd app&&rm -rf "$BITBUCKET_REPO_SLUG"&&git clone -b "$BITBUCKET_BRANCH" --single-branch "$BITBUCKET_GIT_SSH_ORIGIN"&&cd "$BITBUCKET_REPO_SLUG"&&source deploy-dev.sh;"
            - ssh -i ~/.ssh/config $USER_NAME@$DEV_ADDRESS -p $PORT $DIPLOY_COMMAND
